global using StudyPlannerApplication.Domain.Features.UserManagement.Login;
global using Microsoft.AspNetCore.Components.Authorization;
global using Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage;
global using StudyPlannerApplication.Domain.Features.Common;
global using System.Security.Claims;
global using StudyPlannerApplication.App.Services.Security;
global using StudyPlannerApplication.Shared.Enums;
global using Microsoft.EntityFrameworkCore;
global using StudyPlannerApplication.Domain.Features.Subject;
